# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cL6BMchUYbJjdAlC6MQu_xp73853Fw4f
"""

!pip install duckdb

import duckdb
import pandas as pd
# Connect to your project database
con = duckdb.connect(database='project1_finance.duckdb')

# 1. Get a list of all tables in the current schema
tables = con.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'main'").fetchall()

# 2. Loop through and drop each one
if tables:
    for table in tables:
        table_name = table[0]
        con.execute(f"DROP TABLE IF EXISTS {table_name}")
        print(f"Purged: {table_name}")
else:
    print("No tables found to purge.")

# 3. Optional: Verify the database is empty
print("Remaining tables:", con.execute("SHOW TABLES").fetchall())

import os

for f in ['stocks.parquet', 'working_file_1.parquet']:
    if os.path.exists(f):
        size = os.path.getsize(f)
        with open(f, 'rb') as fh:
            fh.seek(-4, 2)
            footer = fh.read(4)
            print(f"File: {f} | Size: {size} bytes | Footer: {footer}")

import duckdb
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler

# --- TABLE 4: The Relational Link (Your Holdings) ---
holdings_df = pd.DataFrame({
    'ticker': ['AAPL', 'MSFT', 'GOOG', 'DRYS'],
    'shares_owned': [50, 20, 10, 100]
})
con = duckdb.connect(database='portfolio_analysis.duckdb')

# Load Fact Tables from Parquet (Storage Bonus: 2pts)
con.execute("CREATE TABLE IF NOT EXISTS bonds AS SELECT * FROM read_parquet('bonds.parquet')")
con.execute("CREATE TABLE IF NOT EXISTS etfs AS SELECT * FROM read_parquet('etfs.parquet')")
con.execute("CREATE TABLE IF NOT EXISTS holdings AS SELECT * FROM holdings_df")
con.execute("CREATE TABLE IF NOT EXISTS stocks AS SELECT * FROM read_parquet('stocks.parquet')")

# Create D' (The Secondary Dataset) with 10-Year Filter
con.execute("""
    CREATE OR REPLACE TABLE secondary_data AS
    SELECT
        s.date,
        SUM(s.close * h.shares_owned) AS portfolio_value,
        AVG(b."Adj Close") AS bond_rate,
        AVG(e.close) AS market_benchmark
    FROM stocks s
    JOIN bonds b ON s.date = b.date
    JOIN etfs e ON s.date = e.date
    JOIN holdings h ON s.ticker = h.ticker
    WHERE s.date >= '2016-01-01'
    GROUP BY s.date
""")

df = con.execute("SELECT * FROM secondary_data ORDER BY date").df().dropna()

import duckdb
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
con = duckdb.connect(database='portfolio_analysis.duckdb')
df = con.execute("SELECT * FROM secondary_data ORDER BY date").df().dropna()
df

# 1. Define Features and Target
X = df[['bond_rate', 'market_benchmark']]
y = df['portfolio_value']

# 2. Standardize to prevent coefficient "explosion"
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3. Implement the Model (Ridge)
# We use Ridge because the 'penalty' makes it a more secure/stable choice
model = Ridge(alpha=1.0)
model.fit(X_scaled, y)

# 4. Final Results for your Report
print(f"Project R-squared: {model.score(X_scaled, y):.4f}")
print(f"Bond Coefficient: {model.coef_[0]:.2f}")
print(f"Market Coefficient: {model.coef_[1]:.2f}")

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd

# 1. Ensure Date is a datetime object
df['date'] = pd.to_datetime(df['date'])

# 2. Setup the Plot
fig, ax = plt.subplots(figsize=(12, 6))

# 3. Plotting your relational data (D')
ax.plot(df['date'], df['portfolio_value'], label='My Portfolio Value', color='blue', linewidth=2)

# Scaling the market trend to match the portfolio's visual height
market_scaled = df['market_benchmark'] * (df['portfolio_value'].mean() / df['market_benchmark'].mean())
ax.plot(df['date'], market_scaled, label='Market Trend (Forecasted)', color='orange', linestyle='--')

# 4. FIXING THE X-AXIS (Month Increments)
# This puts a tick at the start of every month
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=1))
# This formats the label to show "Month Year" (e.g., Jan 2016)
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
plt.xticks(rotation=45)

# 5. Labels and Titles (Rubric Requirements)
ax.set_ylabel("Value in USD ($)", fontsize=12)
ax.set_xlabel("Timeline (Monthly)", fontsize=12)
ax.set_title(f"Portfolio Performance vs. Market Trend ({df['date'].min().year}-{df['date'].max().year})", fontsize=14)
ax.legend(loc='upper right')
ax.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()